# Generated by Django 6.0.3 on 2026-05-08 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='history',
            name='restaurant',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='visited_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='history',
            name='restaurant_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='yelp_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(condition=models.Q(('yelp_id__isnull', False)), fields=('user', 'yelp_id'), name='unique_user_saved_restaurant'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
