# Generated by Django 6.0.3 on 2026-05-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_favorited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='yelp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
